version: 5.2.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    Install-Product node 8.9

    node -v

    npm -v

    npm install -g npm@5.2.0 --loglevel=error

    npm install -g @angular/cli@1.5.5 --loglevel=error

before_build:
- ps: dotnet restore
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build:
  project: IsraelHiking.sln
  parallel: true
  verbosity: minimal
